### ISSUE TITLE
CORS problem

### ISSUE THREAD

**Issue by Jempan** [khaines/angular-applicationinsights#22]
I get "XMLHttpRequest cannot load https://dc.services.visualstudio.com/v2/track. Request header field Authorization is not allowed by Access-Control-Allow-Headers" error whenever I try to use applicationInsightsService. What am I missing?

**Comment by khaines** [comment]
Is this still happening? The CORS headers are controlled by dc.services.visualstudio.com and not this library, so it might be an indication of something larger.

**Comment by Jempan** [comment]
The error went away when I removed angular-applicationinsights so I choose to implement my own simple angular service for application insights for now. Great initiative with this plugin though and thanks for you answer!

**Comment by khaines** [comment]
ok now i read your message again and I understand what happened. You tried to send an Auth header to the tracking endpoint... which is not allowed per it's policy (Access-Control-Allow-Headers:Origin, X-Requested-With, Content-Type, Accept). If you found a work around using another method, great. I would be interested to know if you are still sending authorization header though, because if that's working for you now, then there has to be a way to port that back into this library.
